name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  

  test:
    runs-on: ${{ matrix.platform }}
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    strategy:
      matrix:
        python-version: [ 3.8]
        platform: [ubuntu-latest]
        exclude: # Only test on the oldest and latest supported stable Python on macOS and Windows.
          - platform: macos-latest
            python-version: 3.7
          - platform: macos-latest
            python-version: 3.8
          - platform: windows-latest
            python-version: 3.7
          - platform: windows-latest
            python-version: 3.8
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packages
      run: pip install tox coverage
    - name: Run Tox
      run: tox -e py-cov
    - name: Run Tox without lxml
      run: tox -e py-cov-nolxml
    - name: Produce coverage files
      run: |
        coverage combine
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

  
